- type: scene
  id: default
  location: default
  characters:
    - cat
  dialogs:
    - name: Кот
      text: Привет, это тестовая шняга, показать приколы?
      skipDialog: true
      action:
        !type:LoadButtons
        buttons:
          - name: Да
            dialogAction:
              !type:LoadSceneAction
              prototype: meowyes
          - name: Нет
    - name: Вы
      text: Нет.. пожалуй
    - name: Кот
      text: Ну как хотите
      
- type: scene
  id: meowyes
  location: default
  characters:
    - cat
    - raveel
  dialogs:
    - name: Вы
      text: Да.. пожалуйста..
    - name: Кот
      text: Хм.. что бы мне показать?
    - name: Кот
      text: "*пожимает плечами*"
      delay: 50
    - name: Вы
      text: Хм..