- type: scene
  id: default1
  location: default
  characters:
    - entity: cat
  dialogs:
    - name: Кот
      text: Привет, это тестовая шняга, показать приколы?
      skipDialog: true
      buttons:
        - name: Да
          dialogAction:
            !type:LoadSceneAction
            prototype: meowyes
        - name: Нет
    - name: Вы
      text: Нет.. пожалуй
    - name: Кот
      text: ТЫ ПОНИМАЕШЬ Я ВО АВГАНИСТАНЕ ВОЕВАЛ!!!
    - name: Кот
      text: ЧУРКА!
      
- type: scene
  id: meowyes
  location: default
  characters:
    - entity: cat
  dialogs:
    - name: Вы
      text: Да.. пожалуйста..
    - name: Кот
      text: Хм.. что бы мне показать?
    - name: Кот
      text: "*пожимает плечами*"
      delay: 50
    - name: Вы
      text: Хм..