- type: scene
  id: default1
  location: default
  characters:
    - entity: cat
  dialogs:
    - actions:
        - !type:AudioAction
          prototype: test
    - name: Кот
      text: Тест эффектов да
    - actions:
        - !type:LoadEffectButtonAction