- type: scene
  id: default1
  location: default
  characters:
    - cat
  dialogs:
    - name: Кот
      text: Мне... помяукать?
      skipDialog: true
      action:
        !type:LoadButtons
        buttons:
          - name: Да
            dialogAction:
              !type:LoadSceneAction
              prototype: meowyes
          - name: Нет
    - name: Вы
      text: Нет.. пожалуй
    - name: Кот
      text: Ф..фух..
      
- type: scene
  id: meowyes
  location: default
  characters:
    - cat
  dialogs:
    - name: Вы
      text: Да.. пожалуйста..
    - name: Кот
      text: Х.. хорошо
    - name: Кот
      text: "*мявкает*"
      delay: 50
    - name: Кот
      text: Это
      skipDialog: true
      delay: 50
    - name: Кот
      text: ...
      delay: 100
      skipDialog: true
      newDialog: false
    - name: Кот
      text: "Было странно >:("
      delay: 50
      newDialog: false
    - name: Вы
      text: Да.. есть такое..