- type: scene
  id: default1
  location: default
  characters:
    - entity: cat
  dialogs:
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Generic
    - name: Кот
      text: Тест Generic
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: PaddedCell
    - name: Кот
      text: Тест PaddedCell
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Room
    - name: Кот
      text: Тест Room
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Bathroom
    - name: Кот
      text: Тест Bathroom
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: ConcertHall
    - name: Кот
      text: Тест ConcertHall
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Arena
    - name: Кот
      text: Тест Arena
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Hallway
    - name: Кот
      text: Тест Hallway
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Plain
    - name: Кот
      text: Тест Plain
      
    - actions:
        - !type:AudioAction
          prototype: gymEnter
          effect: Psychotic
    - name: Кот
      text: Тест Psychotic