using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Cinka.Game.UserInterface.Systems.Background;

public sealed class BackgroundControl : Control
{
    public readonly Dictionary<string,TextureRect> Backrounds = new(); 
    public BackgroundControl()
    {
        IoCManager.InjectDependencies(this);
    }

    public void Ensure(Texture texture, string id)
    {
        if (!Backrounds.TryGetValue(id, out var textureRect))
        {
            var rect = new TextureRect()
            {
                Texture = texture,
                HorizontalExpand = true,
                VerticalExpand = true
            };
            Backrounds.Add(id, rect);
            AddChild(rect);
            LayoutContainer.SetAnchorPreset(rect,LayoutContainer.LayoutPreset.Wide);
            return;
        }

        textureRect.Texture = texture;
    }

    public void Remove(string id)
    {
        if(!Backrounds.Remove(id, out var rect)) 
            return;
        
        RemoveChild(rect);
    }
}