- type: parallax
  id: Default
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/test_obl.png"
      tiled: true
      slowness: 0.5
      scrolling: 0.25,0.1
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/test_parallax.png"