- type: scene
  id: default1
  location: default
  characters:
    - entity: cat
  dialogs:
    - actions:
        - !type:AudioAction
          prototype: test
    - name: Кот
      text: Тест эффектов да
      actions:
        - !type:LoadEffectButtonAction

- type: entity
  id: back_default
  components:
    - type: Background
      layer:
        sprite: Backgrounds/pole.rsi

- type: audio
  id: test
  audio: "/Audio/Gym/val.ogg"
  isBackground: true
  
- type: location
  id: default
  background: back_default