using System.Threading.Tasks;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Cinka.Game.UserInterface.Systems.Dialog.Widgets;

[GenerateTypedNameReferences]
public sealed partial class DialogGui : UIWidget
{
    public DialogUIController _dialogUiController;
    public Label? currentLabel;
    public DialogGui()
    {
        RobustXamlLoader.Load(this);
        _dialogUiController = UserInterfaceManager.GetUIController<DialogUIController>();
        _dialogUiController.RegisterDialog(this);
    }

    public Label AppendLabel()
    {
        var label = new Label();
        TextContainer.AddChild(label);
        return label;
    }

    public void AppendText(string text)
    {
        var label = AppendLabel();
        label.Text = text;
    }

    public void AppendLetter(char let)
    {
        if (currentLabel == null)
            NewLabel();
        
        currentLabel.Text += let;
    }

    public void NewLabel()
    {
        currentLabel = new Label();
        TextContainer.AddChild(currentLabel);
    }
    
    public void ClearText()
    {
        TextContainer.DisposeAllChildren();
        currentLabel = null;
    }
}